project:
  type: website
  output-dir: docs

website: 
  page-navigation: true
  title: "Reformational Philosophy and Ethics of Technology (RPET)"
  description: "A website dedicated to the Reformational Philosophy and Ethics of Technology group."
  site-url: "https://reformational-rpet.github.io/"
  favicon: "files/Calvin_College.png"
# author: 
#   - name: "Your Name"
#     email: "your.email@example.com"
format:
  html:
    self_contained: true
    toc: true
    toc_depth: 2
    number_sections: true
    theme: "cosmo"
    css: styles.css
site:
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Members"
        href: members.qmd
      - text: "Agenda"
        href: agenda.qmd
  footer: "© 2025 Reformational Philosophy and Ethics of Technology (RPET)"