project:
  type: website
  output-dir: docs

website:
  title: "RPET"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - meetings.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



