project:
  type: website
  output-dir: docs

website:
  title: "Reformational Philosophy and Ethics of Technology (RPET)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - blog.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



